### ISSUE TITLE
Cloud Variables not saving to local storage correctly

### ISSUE THREAD

**Issue by Bytlitz** [TurboWarp/packager#274]
When I export my game I always make sure to make the could variables store to local storage. But when I make a new version of the game it doesn't save the cloud variable I even tried with HTMLs and it doesn't work. Please Help

**Comment by GarboMuffin** [comment]
To be clear, the problem is that your variables aren't being saved when you generate a new project, yes?

By default the packager uses the project's filename as a unique ID for storing cloud variables. If that changes, the variables also change. You can override that behavior in the advanced settings menu with the "Project ID" option

**Comment by Bytlitz** [comment]
omg thank you
