### ISSUE TITLE
MacOS Version  does not work

### ISSUE THREAD

**Issue by teddinotteddy** [TurboWarp/packager#32]
So I tried converting a scratch project into a Mac compatible application but when I had tried to open the file it would not let me saying quote “The publisher cannot be verified therefore it cannot checked for viruses” or something along those lines. I would like to see this fixed so that I can use the turbo warp packager.

**Comment by GarboMuffin** [comment]
Yeah packaging for macOS is really complicated because of Apple shenanigans. If you want to get rid of that message, either:

a) Tell users to manually go to Finder and right click > open > open anyways, or
b) Give apple $100/yr so that you can sign it and avoid that prompt entirely (I have not done this and don't intend to)

Nothing else I can do

**Comment by teddinotteddy** [comment]
Well at least there is a way for you to use the application. Thanks for your help!
