### ISSUE TITLE
Advice:adding an updater

### ISSUE THREAD

**Issue by ScratchCoder135** [TurboWarp/packager#329]
If it's possible,I wish there's a function of auto updating the projects on PC,it's too complicated to tell users to download again the new version every time when my project updated.Please add it if possible.It would be great if Linux and Windows 64bit support this function.

**Comment by GarboMuffin** [comment]
Automatically updating a project is out of scope for the packager. Doing it safely, securely, efficiently, and reliably on a wide variety of machines is not easy to implement and teach people how to use.

Websites generally don't have this problem, which is another reason the site encourages using a website instead of a desktop application.
