### ISSUE TITLE
Cloud Variables don't work

### ISSUE THREAD

**Issue by pringlepyoru** [TurboWarp/packager#353]
I'm using the Primitive-Cloud-Server by Sheep Tester as my Server, whenever I use the Packager to compile my project it doesn't seem to work at all, not on the local server nor the public server address. Packaging via the Htmlifier works fine with both forms of addresses (local and public) yet the only option that works with Cloud Variables on the Turbowarp Packager is "Store In Local Storage"; what am I doing wrong?

**Comment by cataghg** [comment]
Go to advanced and set project id to a 4 digit number instead of the default stuff. It worked for me.

**Comment by GarboMuffin** [comment]
Third-party cloud variable servers are beyond what I can officially provide support for.

My guess is that you have to change the project ID in the advanced settings to be something less weird looking (like, a number) because primitive-cloud-server is much pickier about the ID than clouddata.turbowarp.org

If that doesn't work, open the developer console with your project open and post a screenshot of the logs.
