### ISSUE TITLE
Electron app opens new browser window with redirect

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#454]
When I change the redirect variable inside a electron app, it just opens a new browser tab.

**Comment by cataghg** [comment]
A link to YouTube

**Comment by GarboMuffin** [comment]
This is intentional. Usually opening these links in the browser what you want.

If you disagree, you can edit packaged-project/resources/app/electron-main.js and replace

```js
const isResourceURL = (url) => {
  try {
    const parsedUrl = new URL(url);
    return parsedUrl.protocol === 'file:' && parsedUrl.href.startsWith(resourcesURL);
  } catch (e) {
    // ignore
  }
  return false;
};
```

with

```js
const isResourceURL = () => true;
```

I feel like this is the fourth time I've had to document something like this so maybe there should be a builtin option for this

**Comment by cataghg** [comment]
Yeah, it should be a option at this point. Previously I removed
```
  contents.on('will-navigate', (e, url) => {
    e.preventDefault();
    openLink(url);
  });
```
and it worked just fine, but now it's being wacky sometimes, for example redirect works when I do this, but new tab opens a browser still, it's inconsistent and annoying. Maybe a "Open links in browser" option should get added.
