### ISSUE TITLE
Where can I find a server for my variables in the cloud?

### ISSUE THREAD

**Issue by VenturaMD21** [TurboWarp/packager#519]
Hello, I am looking for a way to save some variables in the cloud, can someone help me find a free server or help me create one?

**Comment by TheCreatorrr333** [comment]
You don't need an external server - You can use the built in turbowarp server,
Just create a cloud variable and it should work (on https://turbowarp.org or on TurboWarp Desktop)
I personally use TurboWarp Desktop, because it offers also other options which i think are not available/even if they were available they'd be hard to manage
Also: read this: https://docs.turbowarp.org/cloud-variables

**Comment by GarboMuffin** [comment]
If you want to set up your own server, see https://github.com/TurboWarp/cloud-server or https://github.com/SheepTester/primitive-cloud-server
