### ISSUE TITLE
HTML environment doesn't work in Chrome if project's encoded size exceeds ~512MB

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#528]
The HTML file is only 3 MB (which is weird as my original .sb3 file is like 600 MB large). Then I get this error:
![image](https://user-images.githubusercontent.com/82514000/191843493-1ecab49c-9bfc-480f-89df-88af52d6baa8.png)

**Comment by GarboMuffin** [comment]
Does it happen if you use an older version of the packager such as https://github.com/TurboWarp/packager/releases/tag/v1.2.0 ?

**Comment by Alestore** [comment]
Yes, it happens also on this version.

**Comment by GarboMuffin** [comment]
It looks like the way we generate projects breaks if they get too large

Maybe it works in Firefox instead of Chrome?

You could send the project to the usual place (contact@turbowarp.org) and I may be able to take a deeper look

**Comment by Alestore** [comment]
I sent you the email with the project.

**Comment by GarboMuffin** [comment]
Your project is at an interesting point where its encoded data is larger than Chrome's max string length (~512MB)

For now it should work if you use environments like zip or any of the Electron ones, just not as a single HTML file or using the preview button. If those environments are also broken then there's something else going wrong and I'd like to know about that.

Fixing the HTML environment will require a good bit of work that I don't have much time for (generating bytes instead of strings)

**Comment by Alestore** [comment]
OK thanks. Others work properly. The idea was to include the packaged project in HTML and insert it in AppInventor to have an Android application. I also found something about being able to unzip .zip archives within AppInventor so I'll take a look.

**Comment by PPPDUD** [comment]
> OK thanks. Others work properly. The idea was to include the packaged project in HTML and insert it in AppInventor to have an Android application. I also found something about being able to unzip .zip archives within AppInventor so I'll take a look.

Sorry if I am derailing the conversation, but can you please send me a link to where you heard that? I could really use this kind of thing.
