### ISSUE TITLE
Will I get into any legal issues if I completely replace the main license of my program?

### ISSUE THREAD

**Issue by PPPDUD** [TurboWarp/packager#560]
^

**Comment by GarboMuffin** [comment]
Disclaimer: I am not a lawyer, this is not legal advice

What do you mean by "the license of my program"? If you own everything in the project, then you have nothing to worry about. If you're talking about the packager's license, that's more complicated than I want to explain right now (you shouldn't have to worry about the packager's license, though).

**Comment by PPPDUD** [comment]
Is the packager's license the license of the TurboWarp Packager or is it
the license of products made by the packager?

**Comment by GarboMuffin** [comment]
Disclaimer: I am not a lawyer, this is not legal advice

The license of the packager may extend to the files generated by it because the files generated by the packager include significant portions of the packager.

You can read the license here: https://github.com/TurboWarp/packager/blob/master/LICENSE. It's a very standard license used by many large open source projects and corporations.

It really shouldn't pose a problem for you. Legally required copyright notices should already be added for you.

**Comment by PPPDUD** [comment]
Thanks.
